### ISSUE TITLE
關於FLAGS的錯誤

### ISSUE THREAD

**Issue by Albttt** [Tira-tw/Best-Nuke-Bot#1]
我在運行node src/index.js出現以下錯誤
const nuker = new Client({ intents: Object.values(Intents.FLAGS).reduce((a, b) => a + b) });
                                                          ^

TypeError: Cannot read properties of undefined (reading 'FLAGS')
    at Object.<anonymous> (C:\Users\user\Downloads\Best-Nuke-Bot-main\Best-Nuke-Bot-main\src\index.js:6:59)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
 請問這是哪裡出問題?

**Comment by Tira-tw** [comment]
> 我在運行node src/index.js出現以下錯誤 const nuker = new Client({ intents: Object.values(Intents.FLAGS).reduce((a, b) => a + b) }); ^
> 
> TypeError: Cannot read properties of undefined (reading 'FLAGS') at Object. (C:\Users\user\Downloads\Best-Nuke-Bot-main\Best-Nuke-Bot-main\src\index.js:6:59) at Module._compile (node:internal/modules/cjs/loader:1358:14) at Module._extensions..js (node:internal/modules/cjs/loader:1416:10) at Module.load (node:internal/modules/cjs/loader:1208:32) at Module._load (node:internal/modules/cjs/loader:1024:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) at node:internal/main/run_main_module:28:49 請問這是哪裡出問題?

![image](https://github.com/Tira-tw/Best-Nuke-Bot/assets/64715639/15b6715c-5802-4ed9-b9c5-9cdf57b7fd35)


試著重新安裝node.js/npm install/重新下載檔案
我測試是沒問題的
